const fields = {
  '1': 'organization',
  '2': 'hhTaxId',
  '2_1': 'category',
  '3': 'vulnerabilities',
  '4': 'pfuCheck',
  '5': 'surname',
  '6': 'givenName',
  '7': 'additionalName',
  '8': 'gender',
  '9': 'birthday',
  '10': 'admin1',
  '11': 'admin2',
  '12': 'admin3',
  '13': 'admin4',
  '14': 'street',
  '15': 'recentAdmin1',
  '16': 'recentAdmin2',
  '17': 'recentAdmin3',
  '18': 'recentAdmin4',
  '19': 'recentStreet',
  '20': 'taxId',
  '21': 'documentType',
  '22': 'documentNumber',
  '23': 'idpDate',
  '24': 'idpNumber',
  '25': 'iban',
  '26': 'phone',
  '27': 'paid',
  '28': 'notPaid',
  '29': 'supportIsNotProvided',
  '30': 'reasonOfNotProviding'
}

export default fields
